kind: NamespaceSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: fleet-scope-selector
spec:
  mode: dynamic
  selector:
    matchLabels: 
      fleet.gke.io/fleet-scope: acme-corp-products-team
---
### from https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  annotations:
    configmanagement.gke.io/namespace-selector: fleet-scope-selector
spec:
  podSelector: {}
  policyTypes:
  - Ingress
