kind: NamespaceSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: fleet-scope-selector
spec:
  mode: dynamic
  selector:
    matchLabels:
      ## change the hex suffix to the name your scope gets from terraform
      ## in reality, this would be a fixed name within a fleet. 
      fleet.gke.io/fleet-scope: gkee-fleet-tf-80890664
---
### from https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  annotations:
    configmanagement.gke.io/namespace-selector: fleet-scope-selector
spec:
  podSelector: {}
  policyTypes:
  - Ingress
