---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: flux-reconciler
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: flux-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-reconciler
subjects:
- kind: ServiceAccount
  namespace: default
  name: flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sync
  namespace: default
spec:
  interval: 1m0s
  path: {{ .Values.git.path }}
  prune: true
  serviceAccountName: flux
  sourceRef:
    kind: GitRepository
    name: repo
---
