---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sync
  namespace: flux-system
spec:
  interval: 1m0s
  path: {{ .Values.git.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo
