apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: economy-compute-class
spec:
  nodePoolAutoCreation:
    enabled: true
  priorities:
    # start with n2 if spot is available, then go to e2
    - machineType: "n2-standard-2"
      spot: true
    - machineType: "e2-standard-2"
  autoscalingPolicy:
    consolidationDelayMinutes: 1
  activeMigration:
    optimizeRulePriority: true
