apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: llama3-base-model
spec:
  modelName: {{ .Values.model | quote }}
  criticality: Critical
  poolRef:
    name: {{ .Values.app }}
